### ISSUE TITLE
register error fail to instance service 

### ISSUE THREAD

**Issue by jinnzy** [SkyAPM/go2sky#26]
**Describe the bug**
Prompt the following information when I run
```
go2sky-gRPC2019/08/10 12:41:20 the id of service 'gin-server111' is 3
go2sky-gRPC2019/08/10 12:41:20 register error fail to instance service 
go2sky-gRPC2019/08/10 12:41:21 the id of instance '1948345b-bb29-11e9-853c-0a002700000c' id is 10
```
**To Reproduce**
```
	re, err := reporter.NewGRPCReporter("192.168.56.122:11800")
	if err != nil {
		log.Fatalf("new reporter error %v \n", err)
	}
	defer re.Close()
	tracer, err := go2sky.NewTracer("gin-server", go2sky.WithReporter(re))
	if err != nil {
		log.Fatalf("create tracer error %v \n", err)
	}
	tracer.WaitUntilRegister()
	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	r.GET("/user/:name", func(c *gin.Context) {
		name := c.Param("name")
		c.String(200, "Hello %s", name)
	})
	//Use go2sky middleware with tracing
	r.Use(Middleware(r, tracer))
```

**Expected behavior**
Register log reporter

**Additional context**

skywalking opa 6.2.0
ui 6.2.0
golang gin middleware
https://github.com/SkyAPM/go2sky/tree/master/plugins/gin
```
version: '3.3'
services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    image: elasticsearch:6.4.3
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  oap:
    image: apache/skywalking-oap-server:6.2.0
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
  ui:
    image: apache/skywalking-ui:6.2.0
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800
```
![image](https://user-images.githubusercontent.com/33449123/62817692-7b8a4780-bb6d-11e9-96a0-ed024a70678f.png)
